// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: images.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images
    (filename, description, metadata)
VALUES
    ($1, $2, $3)
RETURNING id, filename, description, metadata, created_at
`

type CreateImageParams struct {
	Filename    string                `json:"filename"`
	Description sql.NullString        `json:"description"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, createImage, arg.Filename, arg.Description, arg.Metadata)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getImage = `-- name: GetImage :one
SELECT id, filename, description, metadata, created_at
FROM images
WHERE filename = $1
`

func (q *Queries) GetImage(ctx context.Context, filename string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImage, filename)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getImageDetails = `-- name: GetImageDetails :one
SELECT filename, metadata, description
FROM images
WHERE filename = $1
`

type GetImageDetailsRow struct {
	Filename    string                `json:"filename"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	Description sql.NullString        `json:"description"`
}

func (q *Queries) GetImageDetails(ctx context.Context, filename string) (GetImageDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getImageDetails, filename)
	var i GetImageDetailsRow
	err := row.Scan(&i.Filename, &i.Metadata, &i.Description)
	return i, err
}
