// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

type Image struct {
	ID          int32                 `json:"id"`
	Filename    string                `json:"filename"`
	Description sql.NullString        `json:"description"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	CreatedAt   sql.NullTime          `json:"created_at"`
}
